<!DOCTYPE terms [
<!ELEMENT terms (term+)>
<!ELEMENT term (bg, en, ru)>
<!ELEMENT bg (#PCDATA)>
<!ELEMENT en (#PCDATA)>
<!ELEMENT ru (#PCDATA)>
]>
<terms>
    <term>
        <bg>Водни знаци</bg>
        <en>Watermarks</en>
        <ru>Водяные знаки</ru>
    </term>
    <term>
        <bg>Водни знаци – Каталози</bg>
        <en>Watermarks – Catalogues</en>
        <ru>Водяные знаки – Каталоги</ru>
    </term>
    <term>
        <bg>Водни знаци – Котви</bg>
        <en>Watermarks – Anchors</en>
        <ru>Водяные знаки – Котвы</ru>
    </term>
    <term>
        <bg>Палеография, гръцка</bg>
        <en>Paleography, Greek</en>
        <ru>Палаеография, греческая</ru>
    </term>
    <term>
        <bg>Ръкописи, гръцки</bg>
        <en>Manuscripts, Greek</en>
        <ru>Рукописи, греческие</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски</bg>
        <en>Manuscripts, Slavonic</en>
        <ru>Рукописи, славянские</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Каталози</bg>
        <en>Manuscripts, Slavonic – Catalogues</en>
        <ru>Рукописи, славянские – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Факсимиле</bg>
        <en>Manuscripts, Slavonic – Facsimiles</en>
        <ru>Рукописи, славянские – Факсимиле</ru>
    </term>
    <term>
        <bg>Британски острови – Каталози</bg>
        <en>British Isles – Catalogues</en>
        <ru>Британские острова – Каталоги</ru>    
    </term>
    <term>
        <bg>Рукописи, славянски – Британски острови – Каталози</bg>
        <en>Manuscripts, Slavonic – Bristish Isles – Catalogues</en>
        <ru>Рукописи, славянские – Британские острова – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Великобритания – Каталози</bg>
        <en>Manuscripts, Slavonic – Great Britain – Catalogues</en>
        <ru>Рукописи, славянские – Великобритания – Каталоги</ru>
    </term>
    
    <term>
        <bg>Ръкописи, славянски – България – Каталози</bg>
        <en>Manuscripts, Slavonic – Bulgaria – Catalogues</en>
        <ru>Рукописи, славянские – Болгария – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – София – Каталози</bg>
        <en>Manuscripts, Slavonic – Sofia – Catalogues</en>
        <ru>Рукописи, славянские – София – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Хърватия – Каталози</bg>
        <en>Manuscripts, Slavonic – Chroatia – Catalogues</en>
        <ru>Рукописи, славянски – Хорватия – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Хърватия – Каталози</bg>
        <en>Manuscripts, Slavonic – Chroatia – Catalogues</en>
        <ru>Рукописи, славянски – Хорватия – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Загреб – Каталози</bg>
        <en>Manuscripts, Slavonic – Zagreb – Catalogues</en>
        <ru>Рукописи, славянские – Загреб – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Пловдив – Каталози</bg>
        <en>Manuscripts, Slavonic – Plovdiv – Catalogues</en>
        <ru>Рукописи, славянские – Пловдив – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Сърбия – Каталози</bg>
        <en>Manuscripts, Slavonic – Serbia – Catalogues</en>
        <ru>Рукописи, славянские – Сербия – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Белград – Каталози</bg>
        <en>Manuscripts, Slavonic – Belgrade – Catalogues</en>
        <ru>Рукописи, славянские – Белград – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Румъния – Каталози</bg>
        <en>Manuscripts, Slavonic – Romania – Catalogues</en>
        <ru>Рукописи, славянские – Румыния – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Русия - Каталози</bg>
        <en>Manuscripts, Slavonic – Russia – Catalogues</en>
        <ru>Рукописи, славянские – Россия – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Москва – Каталози</bg>
        <en>Manuscripts, Slavonic – Moscow – Catalogues</en>
        <ru>Рукописи, славянские – Москва – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Санкт Петербург – Каталози</bg>
        <en>Manuscripts, Slavonic – Saint Petersburg – Catalogues</en>
        <ru>Рукописи, славянские – Санкт-Петербург – Каталоги</ru>
    </term>
    <term>
        <bg>Руска Национална библиотека – сбирка на М. П. Погодин</bg>
        <en>Russian National Librarry – Collection of M. P. Pogodin</en>
        <ru>Российская национальная библиотека – Собрание М. П. Погодина</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Гърция, Атон – Каталози</bg>
        <en>Manuscripts, Slavonic – Greece, Athos – Catalogues</en>
        <ru>Рукописи, славянские – Греция, Афон – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Зографски манастир – Каталози</bg>
        <en>Manuscripts, Slavonic – Zograph monastery – Catalogues</en>
        <ru>Рукописи, славянские – Зографский монастырь – Каталоги</ru>
    </term>
    <term>
        <bg>Ръкописи, славянски – Хилендарски манастир – Каталози</bg>
        <en>Manuscripts, Slavonic – Hilandar monastery – Catalogues</en>
        <ru>Рукописи, славянские – Хиландарский монастырь – Каталоги</ru>
    </term>
    <term>
        <bg>Чешка република – Каталози</bg>
        <en>Czech Republic – Catalogues</en>
        <ru>Чешская республика – Каталоги</ru>
    </term>
    
    <term>
        <bg>Ръкописи, славянски – Чешка република – Каталози</bg>
        <en>Manuscripts, Slavonic – Czech Republic – Catalogues</en>
        <ru>Рукописи, славянские – Чешская республика – Каталоги</ru>
    </term>
    <term>
        <bg>Рукописи, славянские – Югославия – Каталози</bg>
        <en>Manuscripts, Slavonic – Yugoslavia – Catalogues</en>
        <ru>Рукописи, славянские – Югославия – Каталоги</ru>
    </term>
    <term>
        <bg>Текстове, гръцки – Издания</bg>
        <en>Texts, Greek – Editions</en>
        <ru>Тексты, греческие – Издания</ru>
    </term>
    <term>
        <bg>Oracula sibyllina</bg>
        <en>Oracula sibyllina</en>
        <ru>Oracula sibyllina</ru>
    </term>
    <term>
        <bg>Оракули, гръцки</bg>
        <en>Oracles, Greek</en>
        <ru>Оракули, гръцки</ru>
    </term>
    <term>
        <bg>Владислав Граматик</bg>
        <en>Vladislav the Grammarian</en>
        <ru>Владислав Грамматик</ru>
    </term>
    <term>
        <bg>Завет на Авраам</bg>
        <en>Testament of Abraham</en>
        <ru>Завет Авраама</ru>
    </term>
    <term>
        <bg>Производство на хартия – Литва – История</bg>
        <en>Papermaking – Lithuania – History</en>
        <ru>Производство бумаги – Литва – История</ru>
    </term>
    <term>
        <bg>Агиография, Християнска – Библиография</bg>
        <en>Hagiography, Christian – Bibliography</en>
        <ru>Агиография, Християнская – Библиография</ru>  
    </term>
    <term>
        <bg>Християнски светци – Биографии – Библиография</bg>
        <en>Christian Saints – Biographies – Bibliography</en>
        <ru>Християнские святые – Биографии – Библиография</ru>
    </term>
</terms>
